# Generated by Django 5.2.4 on 2025-07-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('shift_time', models.CharField(max_length=50)),
            ],
        ),
    ]
