# Generated by Django 5.2.4 on 2025-07-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
            ],
        ),
    ]
